# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20170212_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='choices_en',
            new_name='choices_uk_UA',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='default_en',
            new_name='default_uk_UA',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='help_text_en',
            new_name='help_text_uk_UA',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='label_en',
            new_name='label_uk_UA',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='placeholder_text_en',
            new_name='placeholder_text_uk_UA',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='button_text_en',
            new_name='button_text_uk_UA',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='content_en',
            new_name='content_uk_UA',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='email_message_en',
            new_name='email_message_uk_UA',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='email_subject_en',
            new_name='email_subject_uk_UA',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='response_en',
            new_name='response_uk_UA',
        ),
    ]
