# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20170222_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='choices_uk_UA',
            new_name='choices_uk',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='default_uk_UA',
            new_name='default_uk',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='help_text_uk_UA',
            new_name='help_text_uk',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='label_uk_UA',
            new_name='label_uk',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='placeholder_text_uk_UA',
            new_name='placeholder_text_uk',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='button_text_uk_UA',
            new_name='button_text_uk',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='content_uk_UA',
            new_name='content_uk',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='email_message_uk_UA',
            new_name='email_message_uk',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='email_subject_uk_UA',
            new_name='email_subject_uk',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='response_uk_UA',
            new_name='response_uk',
        ),
    ]
