# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_en',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_ru',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
