# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20170212_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='value_en',
            new_name='value_uk_UA',
        ),
    ]
