# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:11
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='category',
            name='content_ru',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='_meta_title_en',
            field=models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='_meta_title_ru',
            field=models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='name_en',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='name_ru',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option1_en',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option1_ru',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option2_en',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='option2_ru',
            field=cartridge.shop.fields.OptionField(max_length=50, null=True, verbose_name='Colour'),
        ),
    ]
