# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0009_auto_20170212_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ManyToManyField(editable=False, to='sites.Site'),
        ),
    ]
